Improve file explorer
Cubxity/typstudio pull request #2
Opened 2023-04-27 14:48 UTC by OlshaMB

I want to improve file explorer usability
# Roadmap

- [x] Create folder
- [ ] Actions on file
    - [ ] Create new file on folder
    - [ ] Delete File

2023-04-27 14:49 UTC, OlshaMB commented
@Cubxity what icons do you use for typstudio?

2023-04-27 14:50 UTC, Cubxity commented
Hi, thank you for contributing! Please mark the PR as draft if this is still W.I.P. Also, `typstudio` uses `pnpm`, please remove `yarn.lock` from the PR.

2023-04-27 14:50 UTC, Cubxity commented
> @Cubxity what icons do you use for typstudio?

Material Icons.

2023-04-27 14:53 UTC, OlshaMB commented
> > @Cubxity what icons do you use for typstudio?
> 
> Material Icons.

Sidequestion: shouldn't you credit them?

2023-04-27 14:54 UTC, OlshaMB commented
> Hi, thank you for contributing! Please mark the PR as draft if this is still W.I.P. Also, `typstudio` uses `pnpm`, please remove `yarn.lock` from the PR.

Could i add `yarn.lock` to `.gitignore`

2023-04-29 15:29 UTC, OlshaMB commented
I think the pr is done. I also needed to confirm dialog to ask before deletion.

2023-05-08 15:46 UTC, Cubxity commented
Hey, can you rebase and resolve the conflicts?

2023-05-09 07:30 UTC, caoimhebyrne requested changes
I have just a few nitpicks

2023-05-09 07:30 UTC, caoimhebyrne commented on src/components/ShellModal.svelte
> +          >
Formatting is awkward here:
```svelte
<button ...>
    Cancel
</button>
```

2023-05-09 10:19 UTC, Cubxity requested changes
I believe that creating directories and files should be hidden in a context menu. This removes clutter from the UI. Same goes for deletion.

2023-05-09 10:19 UTC, Cubxity commented on src/components/ExplorerNode.svelte
> +  $: handleCreateFile = (e: MouseEvent) => {
Why do these functions use subscribe (`$`)?

2023-05-09 10:56 UTC, OlshaMB commented
> I believe that creating directories and files should be hidden in a context menu. This removes clutter from the UI. Same goes for deletion.

Maybe show the icons only on hover?

2023-05-09 12:35 UTC, Cubxity commented
> > I believe that creating directories and files should be hidden in a context menu. This removes clutter from the UI. Same goes for deletion.
> 
> @Cubxity Maybe show the icons only on hover?
> This also will remove clutter, but unlike a context menu you would feel that you are creating it on a directory not on a file explorer

That sounds alright.

2023-06-06 11:32 UTC, Csega commented
Hi Guys!

What is the status of this PR? Can you comment on it? Is it still in progress or just hanging?

Cheers,
Csega

2023-07-16 23:12 UTC, caoimhebyrne commented
Are you continuing this PR @OlshaMB?

2023-07-17 17:43 UTC, OlshaMB commented
yes

2023-07-17 18:54 UTC, OlshaMB commented
Done

2023-07-17 18:54 UTC, OlshaMB commented
@caoimhebyrne Done

2023-08-21 14:59 UTC, Cubxity commented
Could you rebase/resolve conflicts?

2023-10-29 17:14 UTC, caoimhebyrne commented
@OlshaMB are you planning on continuing to maintain this PR? If not, please let us know...

2023-11-08 06:35 UTC, OlshaMB commented
> @OlshaMB are you planning on continuing to maintain this PR? If not, please let us know ☺️

No, I am not planning, I am not interested in typst right now(waiting for html output) and there are too much changes to merge

2023-11-08 12:28 UTC, caoimhebyrne commented
Ok, I will close the PR and open an issue for improving the file explorer.

2023-11-08 12:28 UTC, closed without merging