fix: explicitly add the application name as a menu
Cubxity/typstudio pull request #30
Opened 2023-10-28 11:32 UTC by ChachyDev

tested on macos
if could be tested on windows and linux by somebody would be great

2023-10-28 14:12 UTC, caoimhebyrne requested changes

2023-10-28 14:12 UTC, caoimhebyrne commented on src-tauri/src/main.rs
> +        "typstudio",
Quit should be in the application's menu.

2023-10-28 15:04 UTC, caoimhebyrne requested changes

2023-10-28 15:04 UTC, caoimhebyrne commented on src-tauri/src/main.rs
> +    menu.add_submenu(file_submenu)
Correct me if I'm wrong, but the `Quit` action still shows up in the File submenu on macOS, and it is also still using the `file_quit` custom action on other platforms.

2023-10-28 15:09 UTC, caoimhebyrne requested changes

2023-10-28 15:09 UTC, caoimhebyrne commented on src-tauri/src/main.rs
> +    }
```suggestion
    #[cfg(target_os = "macos")]
    menu = menu.add_submenu(application_menu)
```
should also work.

2023-10-28 16:10 UTC, caoimhebyrne approved these changes

2023-10-29 09:23 UTC, Cubxity approved these changes

2023-10-29 09:23 UTC, merged